package com.enerjistaj.devhub.entity;

/** Log kaydındaki işlem türü (filtrelemede ve raporlamada kullanılır). */
public enum LogAction {
    GIRIS, GIRIS_BASARISIZ, CIKIS, SIFRE_DEGISTIRME, SIFRE_SIFIRLAMA,
    OLUSTURMA, GUNCELLEME, SILME, TAMAMLAMA, YORUM,
    DURUM_DEGISIKLIGI, PROJE_ATAMA, PROJEDEN_CIKARMA, GOREV_AKTARMA,
    AKTIFLESTIRME, PASIFLESTIRME, YETKI_DEGISIKLIGI,
    TALEP, ONAY, RET, GERI_ALMA, KESINLESTIRME, GERI_CEKME, KAYIT,
    YAYIN, BILGI
}
