package com.enerjistaj.devhub.entity;

public enum NotificationType {
    TASK_ASSIGNED, TASK_DUE, TASK_COMPLETED, TASK_COMMENT, TODO_RECEIVED, TODO_REMINDER, TODO_LIST_ADDED, TODO_COMMENT, PROFILE_REQUESTED, PROFILE_DECIDED, LEAVE_REQUESTED, LEAVE_DECIDED, LEAVE_REOPENED, PROJECT_ASSIGNED, STATUS_CHANGED, ANNOUNCEMENT, DOC_REVISION_REQUESTED, DOC_REVISION_DECIDED, ONBOARDING_DONE
}
